// Dummy Data
exports.data=[
    {
        name:'Sherlock House',
        address:'221B Bakers Street',
        location:'London',
        price:2200,
        moveInDate:'2022-8-11',
        propertyType:'House',
        area:2200,
        beds:4,
        bathrooms:4,     
    },
    {
        name:'Watson House',
        address:'230L Lakers Street',
        location:'London',
        price:1500,
        moveInDate:'2022-10-12',
        propertyType:'House',
        area:4000,
        beds:2,
        bathrooms:1,     
    },
    {
        name:'Western Avenue',
        address:'11 street ola',
        location:'New York',
        price:3000,
        moveInDate:'2022-11-12',
        propertyType:'House',
        area:1000,
        beds:2,
        bathrooms:2,     
    },
    {
        name:'Amaan Hilton',
        address:'11 a Road',
        location:'New York',
        price:2500,
        moveInDate:'2023-1-12',
        propertyType:'House',
        area:3000,
        beds:3,
        bathrooms:4,     
    },
    {
        name:'Hilton Carter',
        address:'230L Lakers Street',
        location:'Mumbai',
        price:800,
        moveInDate:'2022-9-12',
        propertyType:'Office',
        area:2000,
        beds:1,
        bathrooms:2,     
    },
    {
        name:'Yorkingel',
        address:'24 Yorkland',
        location:'London',
        price:11520,
        moveInDate:'2022-11-12',
        propertyType:'Office',
        area:6000,
        beds:2,
        bathrooms:1,     
    },
    {
        name:'White House',
        address:'DvC Road',
        location:'New York',
        price:8400,
        moveInDate:'2022-10-12',
        propertyType:'Industry',
        area:7000,
        beds:4,
        bathrooms:4,     
    },
    {
        name:'Palm Harbor',
        address:'23 Palm walks',
        location:'Mumbai',
        price:4000,
        moveInDate:'2022-12-12',
        propertyType:'Industry',
        area:3000,
        beds:1,
        bathrooms:1,     
    },
    {
        name:'Beverly SpringField',
        address:'2312 StoneHenge',
        location:'Mumbai',
        price:990,
        moveInDate:'2023-2-12',
        propertyType:'Industry',
        area:2000,
        beds:5,
        bathrooms:2,     
    },
    {
        name:'Faulkner Ave',
        address:'Folk Street Road',
        location:'New York',
        price:2312,
        moveInDate:'2022-11-12',
        propertyType:'Office',
        area:3000,
        beds:3,
        bathrooms:3,     
    },
    {
        name:'Elementary Residency',
        address:'14 Street Cred',
        location:'Mumbai',
        price:5000,
        moveInDate:'2022-12-12',
        propertyType:'House',
        area:4000,
        beds:7,
        bathrooms:4,     
    },
    {
        name:'Akuma house',
        address:'Street Good',
        location:'New York',
        price:1213,
        moveInDate:'2022-11-12',
        propertyType:'House',
        area:2000,
        beds:1,
        bathrooms:3,     
    },
    {
        name:'Freemangood',
        address:'Morgan Road 12',
        location:'London',
        price:4500,
        moveInDate:'2022-12-12',
        propertyType:'Industry',
        area:10000,
        beds:5,
        bathrooms:6,     
    },
    {
        name:'Easy home',
        address:'Morgle Road 15',
        location:'Mumbai',
        price:2000,
        moveInDate:'2022-12-12',
        propertyType:'House',
        area:10000,
        beds:5,
        bathrooms:6,     
        
    },
];
