exports.data=[
    {
        name:'Palemers House',
        address:'South Delhi',
        city:'London',
        price:2200,
        date:'2022-8-11',
        type:'House',
        area:2200,
        beds:4,
        bathrooms:4,     
    },
    {
        name:'Berverly House',
        address:'Palm Harber',
        city:'London',
        price:1500,
        date:'2022-10-12',
        type:'House',
        area:4000,
        beds:2,
        bathrooms:1,     
    },
    {
        name:'Faulker Avenue',
        address:'Michigan',
        city:'New York',
        price:3000,
        date:'2022-11-12',
        type:'House',
        area:1000,
        beds:2,
        bathrooms:2,     
    },
    {
        name:'Blue Radison',
        address:'Gurgaon',
        city:'New York',
        price:2500,
        date:'2023-1-12',
        type:'House',
        area:3000,
        beds:3,
        bathrooms:4,     
    },
    {
        name:'Crowne Palaza',
        address:'Rohini',
        city:'Mumbai',
        price:800,
        date:'2022-9-12',
        type:'Office',
        area:2000,
        beds:1,
        bathrooms:2,     
    },
    {
        name:'Delhi Technological College',
        address:'Bawana',
        city:'London',
        price:11520,
        date:'2022-11-12',
        type:'Office',
        area:6000,
        beds:2,
        bathrooms:1,     
    },
    {
        name:'Parliament',
        address:'Praagti Maidan Road',
        city:'New York',
        price:8400,
        date:'2022-10-12',
        type:'Industry',
        area:7000,
        beds:4,
        bathrooms:4,     
    },
    {
        name:'Vice City',
        address:'Gta',
        city:'Mumbai',
        price:4000,
        date:'2022-12-12',
        type:'Industry',
        area:3000,
        beds:1,
        bathrooms:1,     
    },
    {
        name:'Adventure Island',
        address:'Rohini',
        city:'Mumbai',
        price:990,
        date:'2023-2-12',
        type:'Industry',
        area:2000,
        beds:5,
        bathrooms:2,     
    },
    {
        name:'Unity House',
        address:'13 Road',
        city:'New York',
        price:2312,
        date:'2022-11-12',
        type:'Office',
        area:3000,
        beds:3,
        bathrooms:3,     
    },
    {
        name:'City Center',
        address:'Noida',
        city:'Mumbai',
        price:5000,
        date:'2022-12-12',
        type:'House',
        area:4000,
        beds:7,
        bathrooms:4,     
    },
    {
        name:'River Bank house',
        address:'Juhu',
        city:'New York',
        price:1213,
        date:'2022-11-12',
        type:'House',
        area:2000,
        beds:1,
        bathrooms:3,     
    },
    {
        name:'Big House',
        address:'Road 12',
        city:'London',
        price:4500,
        date:'2022-12-12',
        type:'Industry',
        area:10000,
        beds:5,
        bathrooms:6,     
    },
    {
        name:'Gaur home',
        address:'Road 15',
        city:'Mumbai',
        price:2000,
        date:'2022-12-12',
        type:'House',
        area:10000,
        beds:5,
        bathrooms:6,     
        
    },
];
